-- local M = {}
--
-- local MAX_BUFFERS = 3
--
-- local function is_visible(bufnr)
--   return vim.fn.bufwinid(bufnr) ~= -1
-- end
--
-- local function enforce_buffer_limit(added_bufnr)
--   local buffers = vim.fn.getbufinfo({ buflisted = 1 })
--   if #buffers <= MAX_BUFFERS then
--     return
--   end
--
--   -- sort by last used (oldest first)
--   table.sort(buffers, function(a, b)
--     return a.lastused < b.lastused
--   end)
--
--   local to_close = #buffers - MAX_BUFFERS
--   local closed = 0
--
--   for _, buf in ipairs(buffers) do
--     if closed >= to_close then break end
--
--     local bufnr = buf.bufnr
--     if
--         bufnr == added_bufnr
--         or vim.api.nvim_buf_get_option(bufnr, "buftype") ~= ""
--         or vim.api.nvim_buf_get_option(bufnr, "modified")
--         or is_visible(bufnr) -- 👈 skip buffers currently visible
--     then
--       goto continue
--     end
--
--     -- attempt to delete; use pcall to avoid breaking if something goes wrong
--     pcall(vim.api.nvim_buf_delete, bufnr, { force = true })
--     closed = closed + 1
--
--     ::continue::
--   end
-- end
--
-- vim.api.nvim_create_autocmd("BufAdd", {
--   callback = function(ev)
--     -- schedule to run right after the event to ensure the new buffer is fully registered
--     vim.schedule(function()
--       enforce_buffer_limit(ev.buf)
--     end)
--   end,
-- })
--
-- return M
